# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 01:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='\u7c7b\u578b\u540d\u79f0')),
                ('order_core', models.IntegerField(default=0, verbose_name='\u6392\u5e8f\u7801')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=72, verbose_name='\u6807\u9898')),
                ('context', models.TextField(verbose_name='\u5185\u5bb9')),
                ('keywords', models.CharField(db_index=True, max_length=36, verbose_name='\u5173\u952e\u8bcd')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('click_rate', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u91cf')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.Category', verbose_name='\u7c7b\u578b')),
            ],
        ),
    ]
