# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': '\u62a5\u4ef7', 'verbose_name_plural': '\u62a5\u4ef7'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': '\u6536\u85cf', 'verbose_name_plural': '\u6536\u85cf'},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='title',
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='\u62a5\u4ef7'),
        ),
    ]
