# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 07:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='\u8d44\u4ea7\u6807\u9898')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='\u8bbf\u95ee\u65f6\u95f4')),
                ('assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Assets', verbose_name='\u8bbf\u95ee\u7684\u8d44\u4ea7')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5934\u50cf')),
                ('mobile', models.IntegerField(verbose_name='\u624b\u673a\u53f7')),
                ('nick_name', models.CharField(max_length=32, unique=True, verbose_name='\u6635\u79f0')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='\u7ecf\u5ea6')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='\u7eac\u5ea6')),
                ('detail_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u8be6\u7ec6\u5730\u5740')),
                ('open_id', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
