# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='browsehistory',
            options={'verbose_name': '\u7528\u6237\u8bbf\u95ee\u5386\u53f2', 'verbose_name_plural': '\u7528\u6237\u8bbf\u95ee\u5386\u53f2'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '\u7528\u6237\u4fe1\u606f', 'verbose_name_plural': '\u7528\u6237\u4fe1\u606f'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=15, verbose_name='\u624b\u673a\u53f7'),
        ),
    ]
