# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 07:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='\u8d44\u4ea7\u540d\u79f0')),
                ('instruction', models.TextField(verbose_name='\u8d44\u4ea7\u8bf4\u660e')),
                ('parms', models.TextField(verbose_name='\u914d\u5957\u4fe1\u606f')),
                ('bond_institution', models.CharField(max_length=32, verbose_name='\u503a\u6743\u673a\u6784')),
                ('obligor', models.CharField(max_length=8, verbose_name='\u503a\u52a1\u4eba')),
                ('guarantee', models.CharField(max_length=8, verbose_name='\u4fdd\u8bc1\u4eba')),
                ('mortgagor', models.CharField(max_length=8, verbose_name='\u62b5\u62bc\u4eba')),
                ('spot', models.TextField(verbose_name='\u8d44\u4ea7\u4eae\u70b9')),
                ('contacts', models.CharField(max_length=8, verbose_name='\u8054\u7cfb\u4eba')),
                ('c_phone', models.CharField(max_length=16, verbose_name='\u8054\u7cfb\u4eba\u7535\u8bdd')),
                ('fax', models.CharField(max_length=16, verbose_name='\u4f20\u771f')),
                ('p_address', models.CharField(max_length=64, verbose_name='\u901a\u8baf\u5730\u5740')),
                ('transaction', models.TextField(verbose_name='\u4ea4\u6613\u5bf9\u8c61')),
                ('statement', models.TextField(verbose_name='\u58f0\u660e')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='AssetsImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large', models.ImageField(upload_to='%Y/%m/%d/')),
                ('middle', models.ImageField(upload_to='%Y/%m/%d/')),
                ('small', models.ImageField(upload_to='%Y/%m/%d/')),
                ('assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Assets', verbose_name='\u8d44\u4ea7')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='\u8d44\u4ea7\u7c7b\u578b')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='\u8bc4\u8bba\u65f6\u95f4')),
                ('asserts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Assets', verbose_name='\u8d44\u4ea7')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8bc4\u8bba\u4eba')),
            ],
        ),
        migrations.AddField(
            model_name='assets',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Category', verbose_name='\u5206\u7c7b'),
        ),
    ]
