# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assets',
            options={'verbose_name': '\u8d44\u4ea7\u4fe1\u606f', 'verbose_name_plural': '\u8d44\u4ea7\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='assetsimg',
            options={'verbose_name': '\u8d44\u4ea7\u56fe\u7247', 'verbose_name_plural': '\u8d44\u4ea7\u56fe\u7247'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '\u8d44\u4ea7\u5206\u7c7b', 'verbose_name_plural': '\u8d44\u4ea7\u5206\u7c7b'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '\u8d44\u4ea7\u8bc4\u8bba', 'verbose_name_plural': '\u8d44\u4ea7\u8bc4\u8bba'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='asserts',
            new_name='assets',
        ),
    ]
